#!/usr/bin/env bash
set -e

##### Dart formatter
printf "\n"
printf "\e[33;1m%s\e[0m\n" 'Running Dart formatter'
dart format ./lib ./test


##### Dart analyzer
printf "\n"
printf "\e[33;1m%s\e[0m\n" 'Running Dart analyzer'
dart analyze --fatal-infos --fatal-warnings ./lib
printf "\e[32;1m%s\e[0m\n" 'Dart analyzer passed'


##### Dart unit tests
printf "\n"
printf "\e[33;1m%s\e[0m\n" 'Running Dart unit tests'
dart test
printf "\e[32;1m%s\e[0m\n" 'All unit tests passed'
